config/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from src import marketplace
from src.accounts.views import HomeView

urlpatterns = [
    path('',  login_required(HomeView.as_view()), name='home'),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('marketplace/', include(('src.marketplace.urls', 'src.marketplace'), namespace='marketplace')),
    path('products/', include(('src.products.urls', 'src.products'), namespace='products'))
]

src/products/urls.py
from django.urls import path

from src.products.views import ProductListView, ProductDatatablesJsonView, SynchronizeProduct

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('json', ProductDatatablesJsonView.as_view(), name='product_list_json'),
    path('sync', SynchronizeProduct.as_view(), name='product_sync')
]

src/products/models.py
from django.db import models

from src.categories.models import Categories
from src.shared.enum import ShopeeStatus


class Products(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    category = models.ForeignKey(Categories, models.SET_NULL, blank=True, null=True)
    shopee_status = models.CharField(choices=ShopeeStatus.choices, max_length=255)
    shopee_id = models.BigIntegerField(null=True, blank=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'products'

    def __str__(self):
        return self.name


class ProductImages(models.Model):
    product = models.ForeignKey(Products, models.CASCADE)
    image = models.ImageField(upload_to='product_images')
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_images'

    def __str__(self):
        return 'Image product {0}'.format(self.product)


class Variants(models.Model):
    name = models.CharField(max_length=255)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_variants'

    def __str__(self):
        return self.name


class Colors(models.Model):
    name = models.CharField(max_length=225)
    hex = models.CharField(max_length=225)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'product_colors'

    def __str__(self):
        return self.name


class ProductsVariantsColors(models.Model):
    product = models.ForeignKey(Products, models.CASCADE)
    variant = models.ForeignKey(Variants, models.SET_NULL, blank=True, null=True)
    color = models.ForeignKey(Colors, models.SET_NULL, blank=True, null=True)
    sku = models.CharField(max_length=225, blank=True, null=True)
    origin_price = models.IntegerField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    volume_length = models.FloatField(blank=True, null=True)
    volume_width = models.FloatField(blank=True, null=True)
    volume_height = models.FloatField(blank=True, null=True)
    stock = models.IntegerField(blank=True, null=True)
    thumbnail_image = models.ImageField(upload_to='thumbnail_image', blank=True, null=True)
    shopee_id = models.BigIntegerField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'products_variants_colors'

    def __str__(self):
        return '{0} {1} {2}'.format(self.product, self.variant, self.color)

src/products/views.py
import hashlib
import json
import hmac
import requests
import time

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction, DatabaseError
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView, View

from src.marketplace.models import Marketplaces
from src.products.models import Products, Colors, Variants, ProductsVariantsColors
from src.shared.enum import MarketplaceName
from src.shared.helpers import refresh_shopee_access_token
from django_datatables_view.base_datatable_view import BaseDatatableView


def get_shopee_product_list(shopee, partner_id, partner_key, offset=0):
    shopee = shopee

    timestamp = int(time.time())
    host = settings.LIVE_HOST
    path = "/api/v2/product/get_item_list"
    code = shopee.code
    shop_id = shopee.shop_id
    access_token = shopee.access_token

    tmp_base_string = "%s%s%s%s%s" % (partner_id, path, timestamp, access_token, shop_id)
    base_string = tmp_base_string.encode()

    sign = hmac.new(bytes(partner_key, 'latin-1'), base_string, hashlib.sha256).hexdigest()

    url = host + path + "?access_token=%s&item_status=%s&offset=%s&page_size=%s&partner_id=%s&shop_id=%s&sign=%s&timestamp=%s" % (
        access_token, 'NORMAL', offset, 100, partner_id, shop_id, sign, timestamp)

    resp = requests.get(url)
    return json.loads(resp.content)


def get_shopee_product_list_base_info(shopee, partner_id, partner_key, product_list):
    shopee = shopee

    timestamp = int(time.time())
    host = settings.LIVE_HOST
    path = "/api/v2/product/get_item_base_info"
    code = shopee.code
    shop_id = shopee.shop_id
    access_token = shopee.access_token
    partner_id = partner_id
    partner_key = partner_key

    tmp_base_string = "%s%s%s%s%s" % (partner_id, path, timestamp, access_token, shop_id)
    base_string = tmp_base_string.encode()

    sign = hmac.new(bytes(partner_key, 'latin-1'), base_string, hashlib.sha256).hexdigest()

    product_list = ','.join(str(x) for x in product_list)

    url = host + path + "?shop_id=%s&need_tax_info=%s&item_id_list=%s&partner_id=%s&need_complaint_policy=%s&access_token=%s&timestamp=%s&sign=%s" % (
        shop_id, 'true', product_list, partner_id, False, access_token, timestamp, sign)

    resp = requests.get(url)
    return json.loads(resp.content)


def get_shopee_variant_product(shopee, partner_id, partner_key, item_id):
    timestamp = int(time.time())
    host = settings.LIVE_HOST
    path = "/api/v2/product/get_model_list"
    code = shopee.code
    shop_id = shopee.shop_id
    access_token = shopee.access_token
    partner_id = partner_id
    partner_key = partner_key

    tmp_base_string = "%s%s%s%s%s" % (partner_id, path, timestamp, access_token, shop_id)
    base_string = tmp_base_string.encode()

    sign = hmac.new(bytes(partner_key, 'latin-1'), base_string, hashlib.sha256).hexdigest()

    url = host + path + "?shop_id=%s&item_id=%s&partner_id=%s&access_token=%s&timestamp=%s&sign=%s" % (
        shop_id, item_id, partner_id, access_token, timestamp, sign)

    resp = requests.get(url)
    return json.loads(resp.content)


class ProductListView(LoginRequiredMixin, TemplateView):
    template_name = 'products/product_list.html'


class ProductDatatablesJsonView(BaseDatatableView):
    columns = ['id', 'product', 'variant', 'color', 'SKU', 'origin_price', 'stock', 'updated_at']

    def get_initial_queryset(self):
        return ProductsVariantsColors.objects.all().order_by('product')

    def filter_queryset(self, qs):
        search = self.request.GET.get(u'search[value]', None)
        qs = qs.filter(is_deleted=False)
        if search:
            qs = qs.filter(product__name__icontains=search)

        return qs

    def prepare_results(self, qs):
        product_variant_list = []
        for product_variant_item in qs:
            product_variant_list.append({
                'id': product_variant_item.pk,
                'product': product_variant_item.product.name,
                'variant': product_variant_item.variant.name.title() if product_variant_item.variant else '-',
                'color': product_variant_item.color.name.title() if product_variant_item.color else '-',
                'SKU': '-',
                'origin_price': product_variant_item.origin_price,
                'stock': product_variant_item.stock,
                'updated_at': product_variant_item.updated_at.strftime("%Y-%m-%d %H:%M:%S")
            })
        return product_variant_list


class SynchronizeProduct(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        if self.request.is_ajax():
            shopee = Marketplaces.objects.filter(name='SHOPEE_LIVE').first()

            shop_id = shopee.shop_id
            access_token = shopee.access_token
            refresh_token = shopee.refresh_token
            partner_id = settings.LIVE_PARTNER_ID
            partner_key = settings.LIVE_KEY

            has_next_page = True
            offset = 0
            product_list = []

            while has_next_page:
                product_list_response = get_shopee_product_list(shopee, partner_id, partner_key, offset)

                if product_list_response['error'] == 'error_auth' and \
                        product_list_response['message'] == 'Invalid access_token.':
                    access_token = refresh_shopee_access_token(shop_id, partner_id, partner_key, refresh_token)
                    product_list_response = get_shopee_product_list(shopee, partner_id, partner_key, offset)

                has_next_page = product_list_response['response']['has_next_page']
                offset = product_list_response['response']['next_offset'] if has_next_page else 0
                items = product_list_response['response']['item']
                for item in items:
                    product_list.append(item['item_id'])
                print(len(product_list))

            detail_product_list = []
            divided_list_by_50 = [product_list[i:i + 50] for i in range(0, len(product_list), 50)]
            for list in divided_list_by_50:
                detail_product_response = get_shopee_product_list_base_info(shopee, partner_id, partner_key, list)
                detail_products = detail_product_response['response']['item_list']

                for detail_product in detail_products:
                    detail_product_list.append(detail_product)

            try:
                with transaction.atomic():
                    for product_item in detail_product_list:
                        product = Products.objects.update_or_create(
                            shopee_id=product_item['item_id'],
                            defaults={
                                'name': product_item['item_name'],
                                'shopee_status': product_item['item_status']
                            }
                        )
                        variant_product_response = get_shopee_variant_product(shopee, partner_id, partner_key,
                                                                              product_item['item_id'])
                        variant_product = variant_product_response['response']

                        color_list = []
                        motif_list = []
                        for variant in variant_product['tier_variation']:
                            if 'warna' in variant['name'].lower():
                                for color_variant in variant['option_list']:
                                    product_color = Colors.objects.get_or_create(name=color_variant['option'].lower())
                                    color_list.append(product_color)
                            elif 'motif' in variant['name'].lower():
                                for motif_variant in variant['option_list']:
                                    product_motif = Variants.objects.get_or_create(name=motif_variant['option'].lower())
                                    motif_list.append(product_motif)

                        for model in variant_product['model']:
                            ProductsVariantsColors.objects.update_or_create(
                                shopee_id=model['model_id'],
                                defaults={
                                    'origin_price': model['price_info'][0]['original_price'],
                                    'stock': model['stock_info_v2']['summary_info']['total_available_stock'],
                                    'color': color_list[model['tier_index'][0]][0] if len(color_list) else None,
                                    'variant': motif_list[model['tier_index'][1]][0] if len(motif_list) else None,
                                    'product': product[0]
                                }
                            )
                    return JsonResponse({
                        'message': 'Sync data success',
                    }, status=200)
            except DatabaseError as e:
                print("Database Error: ")
                return JsonResponse({
                    'message': str(e),
                }, status=400)

templates/products/product_list.html
{% extends 'layout/base_with_nav.html' %}

{% load static %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <form action="#">
      <label class="label_toko" for="">Toko : </label>
      <input type="checkbox" /> Semua
    </form>
  </div>
  <div class="row justify-content-between">
    <div class="col-lg-4 botuna bg-white">
      <form action="#">
        <select name="produk" id="produk">
          <option value="name"> Nama Produk</option>
          <option value="variant">Motif</option>
          <option value="color">Warna</option>
        </select>
        <input type="text" placeholder="Masukan kata kunci" aria-controls="datatable"/>
      </form>
    </div>
    <div class="col-lg-1">
      <button class="btn-reset">Reset</button>
    </div>
  </div>
  <div class="row justify-content-end mt-3">
    <button id="activeButton" class="btn-menu"> >Nonaktifkan</button>
    <button id="syncButton" class="btn-menu" data-toggle="modal" data-target="#syncModal">Sinkronisasi</button>
    <button class="btn-menu" >Hapus</button>
    <button class="btn-menu" >Tambah Produk</button>
    <button class="btn-menu" >Eksplore</button>
  </div>
  <div class="bg-white my-3 mx-3">
    <table id="datatable" style="width: 95%; margin: auto;">
      <thead>
        <tr>
          <th><id></id></th>
          <th>Produk</th>
          <th>Motif</th>
          <th>Warna</th>
          <th>SKU</th>
          <th>Harga</th>
          <th>Stok</th>
          <th>Waktu Pembaruan</th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
</div>
<div class="modal fade" id="syncModal" tabindex="-1" role="dialog" aria-labelledby="syncModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="syncModalTitle">Sync Data In Progress</h5>
      </div>
      <div class="modal-body">
        Sync Data In progress. Please wait for a moment
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="successSyncModal" tabindex="-1" role="dialog" aria-labelledby="success-sync-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="success-sync-modal">Sync Product Data Success!</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Products data has been synchronize.
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="failSyncModal" tabindex="-1" role="dialog" aria-labelledby="fail-sync-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="fail-sync-modal">Sync Product Data Fail!</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Something went wrong, please try again or contact developer.
      </div>
    </div>
  </div>
</div>

{% endblock %}


{% block js_extra %}
<script type="text/javascript">
$(function () {

  var product_table = $('#datatable').DataTable({
    order: [[0, "desc"]],
    columns: [
      {
        data: 'id',
        orderable: true,
        searchable: true
      },
      {
        data: 'product',
        orderable: true,
        searchable: true,
      },
      {
        data: 'variant',
        orderable: true,
        searchable: true,
      },
      {
        data: 'color',
        orderable: true,
        searchable: true,
      },
      {
        data: 'SKU',
        orderable: true,
        searchable: true,
      },
      {
        data: 'origin_price',
        orderable: true,
        searchable: true,
      },
      {
        data: 'stock',
        orderable: true,
        searchable: true,
      },
      {
        data: 'updated_at',
        orderable: true,
        searchable: true,
      },
    ],
    columnDefs: [
      {
        target: 0,
        visible: false,
      },
    ],
    serverSide: true,

    ajax:{
      "processing": true,
      "url": "{% url 'products:product_list_json' %}",
      "dataSrc": "data",
    }
  });

  $('body').on('click', '#syncButton', function(e){
     e.preventDefault();
     $.ajax({
        url: "{% url 'products:product_sync' %}",
        success: function(result) {
          $('#syncModal').modal('hide')
          $('#successSyncModal').modal('show')
          location.reload()
        },
        error: function(result) {
          $('#syncModal').modal('hide')
          $('#failSyncModal').modal('show')
		      location.reload()
        }
    });
  })
})
</script>
{% endblock %}