config/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include

from src import marketplace
from src.accounts.views import HomeView

urlpatterns = [
    path('',  login_required(HomeView.as_view()), name='home'),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('marketplace/', include(('src.marketplace.urls', 'src.marketplace'), namespace='marketplace')),
    path('products/', include(('src.products.urls', 'src.products'), namespace='products'))
]

src/marketplace/urls.py
from django.urls import path

from src.marketplace.views import MarketplaceListView, ShopeeGenerateAuthLink, AuthShopee

urlpatterns = [
    path('', MarketplaceListView.as_view(), name='marketplace_list'),
    path('get_shopee_auth_link', ShopeeGenerateAuthLink.as_view(), name='get_shopee_auth_link'),
    path('get_shopee_access_token', AuthShopee.as_view(), name='get_shopee_access_token')
]

src/marketplace/models.py
from django.db import models


class Marketplaces(models.Model):
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    access_token = models.CharField(max_length=255, blank=True, null=True)
    refresh_token = models.CharField(max_length=255, blank=True, null=True)
    code = models.CharField(max_length=255, blank=True, null=True)
    shop_id = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'marketplaces'

    def __str__(self):
        return self.name

src/marketplace/views.py
import hashlib
import json
import hmac
import requests
import time

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, RedirectView

from src.marketplace.models import Marketplaces
from src.shared.enum import MarketplaceName


class MarketplaceListView(LoginRequiredMixin, TemplateView):
    template_name = 'marketplaces/list.html'


class ShopeeGenerateAuthLink(LoginRequiredMixin, RedirectView):

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        timestamp = int(time.time())
        host = settings.TEST_HOST
        path = "/api/v2/shop/auth_partner"
        redirect_url = "http://127.0.0.1:8000/marketplace/get_shopee_access_token"
        partner_id = settings.TEST_PARTNER_ID
        key = settings.TEST_KEY
        partner_key = key.encode()
        tmp_base_string = "%s%s%s" % (partner_id, path, timestamp)
        base_string = tmp_base_string.encode()
        sign = hmac.new(partner_key, base_string, hashlib.sha256).hexdigest()
        url = host + path + "?partner_id=%s&timestamp=%s&sign=%s&redirect=%s" % (
        partner_id, timestamp, sign, redirect_url)

        return url


class AuthShopee(LoginRequiredMixin, RedirectView):

    def get(self, request, *args, **kwargs):
        code = request.GET.get('code', None)
        shop_id = request.GET.get('shop_id', None)
        partner_id = settings.TEST_PARTNER_ID

        if code and shop_id:
            timestamp = int(time.time())
            host = settings.TEST_HOST
            path = "/api/v2/auth/token/get"
            body = {"code": code, "shop_id": int(shop_id), "partner_id": int(partner_id)}
            tmp_base_string = "%s%s%s" % (partner_id, path, timestamp)
            base_string = tmp_base_string.encode()
            partner_key = settings.TEST_KEY
            sign = hmac.new(bytes(partner_key, 'latin-1'), base_string, hashlib.sha256).hexdigest()
            url = host + path + "?partner_id=%s&timestamp=%s&sign=%s" % (partner_id, timestamp, sign)
            headers = {"Content-Type": "application/json"}
            resp = requests.post(url, json=body, headers=headers)
            ret = json.loads(resp.content)
            access_token = ret.get("access_token")
            new_refresh_token = ret.get("refresh_token")
            Marketplaces.objects.update_or_create(
                name=MarketplaceName.SHOPEE,
                defaults={
                    'access_token': access_token,
                    'refresh_token': new_refresh_token,
                    'code': code,
                    'shop_id': shop_id
                })
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('marketplace:marketplace_list')

templates/marketplaces/list.html
{% extends 'layout/base_with_nav.html' %}

{% load static %}

{% block css_extra %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
{% endblock %}

{% block content %}
<div class="container mb-2 d-flex justify-content-end">
  <a class="btn-integrasi" href="integrasi_toko.html">Integrasi Toko</a>
</div>
<div class="container mb-5">
  <div class="d-flex">
    <div class="col-lg-4">
      <a href="{% url 'marketplace:get_shopee_auth_link' %}" class="card mx-auto">
        <img src="{% static 'img/toko_shopee.png' %}" alt="">
        <h2 class="toko-shopee">Shopee</h2>
      </a>
    </div>
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img src="{% static 'img/toko_tiktok.png' %}" alt="">
        <h2 class="toko-tiktok">Tiktok</h2>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img src="{% static 'img/toko_ig.png' %}" alt="">
        <h2 class="toko-ig">Instagram</h2>
      </div>
    </div>
  </div>
  <div class="d-flex mt-3">
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img src="{% static 'img/toko_fb.png' %}" alt="">
        <h2 class="toko-fb">Facebook</h2>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img src="{% static 'img/toko_wa.png' %}" alt="">
        <h2 class="toko-wa">WhatsApp</h2>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img src="{% static 'img/toko_tele.png' %}" alt="">
        <h2 class="toko-tele">Telegram</h2>
      </div>
    </div>
  </div>
  <div class="d-flex mt-3">
    <div class="col-lg-4">
      <div class="card mx-auto">
        <img class="shadow img-img" src="{% static 'img/icon1.png' %}" alt="">
        <h2 class="offline-store">Offline Store</h2>
      </div>
    </div>
  </div>
</div>
{% endblock %}